### ISSUE TITLE
Add support for hidden bugs

### ISSUE THREAD

**Issue by Gioyik** [bzdeck/bzdeck#242]
Mozilla has a feature to hide a bug from all people except for special groups or people in CC. Same thing with the Reps section in Bugzilla at Mozilla, all the bugs from Reps are hidden.

It's a check box when you fill a bug:
> Many users could be harmed by this security problem: it should be kept hidden from the public until it is resolved.

**Comment by kyoshino** [comment]
Not only security bugs but also marketing stuff can be hidden. +1 anyway to let users know the bug is not accessible.
