### ISSUE TITLE
Crashes after selecting another bug right after submitting comment

### ISSUE THREAD

**Issue by shinglyu** [bzdeck/bzdeck#257]
STR:
1. In the home screen, leave a comment in the bug at the right panel
2. Before the comment is successfully submitted (before the comment shows up in the timeline), click another bug in the left panel
3. Can't switch bugs now.
4. Refresh the page

Expected: 
The page reloads and I can retry submitting commnets

Actual:
BzDeck failed to load with the following error:
  TypeError: BzDeck.views.toolbar is undefined     combined.js:5636:6
  AbortError     combined.js:4352:0

**Comment by shinglyu** [comment]
OK, now I restart firefox nightly completely, and everything goes back to normal. 
The comment was submitted successfully, I can see it in the timeline after firefox restart.

The comment which causes the error is https://bugzilla.mozilla.org/show_bug.cgi?id=1137063#c24

**Comment by kyoshino** [comment]
I'll test this using a [demo server](https://bugzilla-dev.allizom.org/) next week.

**Comment by kyoshino** [comment]
I cannot reproduce the issue so far.

**Comment by kyoshino** [comment]
Please reopen this still happens!
