### ISSUE TITLE
Number of unread bugs in folder title

### ISSUE THREAD

**Issue by shinglyu** [bzdeck/bzdeck#268]
`Inbox` => `Inbox (3)` if there are 3 unread bugs.

I think this will be easier than the folder, I would like to use this as a practice to get myself familiar with the codebase.

**Comment by kyoshino** [comment]
Actually there is a [code to show the number of unread bugs](https://github.com/bzdeck/bzdeck/blob/master/webroot/static/scripts/views/sidebar.js#L57-L67) but it's not working as expected for some reason. So this is a regression :sweat_smile: :sweat_smile: :sweat_smile: I think this can be solved once my [code refactoring](https://github.com/bzdeck/bzdeck/issues/243) is done, hopefully tomorrow.

**Comment by shinglyu** [comment]
lol
