### ISSUE TITLE
Tapping a bug in the Inbox is very difficult

### ISSUE THREAD

**Issue by nt1m** [bzdeck/bzdeck#270]
I have to tap multiple times on the item in order for the bug to show, I have to tap until the item gets blue.
It appears that the mousedown and the click events are logged each time I tap (in the Firefox DevTools), but the app is barely reactive so that confirms that it is an issue on bzdeck's side.

Device : Firefox OS Flame.
B2G 3.0.0 prerelease, with build 20150501010203

**Comment by nt1m** [comment]
This is possibly a perf problem, since bzdeck runs slower than other apps on my device

**Comment by kyoshino** [comment]
Thanks for your report! I have solved the issue in #269. I'm pushing the fix to production in a few minutes.

**Comment by kyoshino** [comment]
This issue should be solved now. I'm fixing a performance regression in #271.
