### ISSUE TITLE
Minify JS and CSS on production

### ISSUE THREAD

**Issue by kyoshino** [bzdeck/bzdeck#273]
#218 combined JS files, but it would be nice to [minify](https://github.com/mrclay/minify) them + CSS as well.

**Comment by shinglyu** [comment]
Also by handwritten PHP? or use some 3rd party tool?

**Comment by kyoshino** [comment]
Maybe this one? https://github.com/mrclay/minify

**Comment by shinglyu** [comment]
(Y)

**Comment by kyoshino** [comment]
I'm not sure we really need this. In #349 the server has upgraded to HTTP/2, so it's already fast. We can also use [Brotli](http://google-opensource.blogspot.ca/2015/09/introducing-brotli-new-compression.html) in the future.
