### ISSUE TITLE
Bug timeline is not updating

### ISSUE THREAD

**Issue by shinglyu** [bzdeck/bzdeck#282]
When I look at bug 1094759, the latest comment is 5 days ago, but the bug on bugzilla has newer comments. 

I tried refreshing the page multiple times but it doesn't update. 

Please let me know if there are any log I can help capturing. 

![screenshot from 2015-05-13 13 57 14](https://cloud.githubusercontent.com/assets/3250983/7604669/7448ab3a-f978-11e4-9cc2-a6dd736eeb6e.png)

**Comment by kyoshino** [comment]
I was about to file this issue. Maybe retrieving data from Bugzilla but failing to update the local database? Hmm. BzDeck doesn't have any logging feature for now :-( We should have it...

**Comment by kyoshino** [comment]
Actually I have added the debug mode in #235 that is described in [README](https://github.com/bzdeck/bzdeck/blob/master/README.md).
We should add `if (BzDeck.config.debug) { console.log(...) }` everywhere.

**Comment by kyoshino** [comment]
Most bugs are updated properly. Will figure out why some are not.

**Comment by shinglyu** [comment]
Perhaps having a `logging` class, and control the global logging level in that? Having debug logic in production code sometimes create more bugs.

**Comment by kyoshino** [comment]
So the logging is now enabled only when `?debug=true` is added to the URL.
