### ISSUE TITLE
Fail to load bug

### ISSUE THREAD

**Issue by shinglyu** [bzdeck/bzdeck#284]
STR:
* Open this bug directly: https://www.bzdeck.com/bug/1165227 (the bug is not in my inbox or any folder)
* The bug loads forever

Notes:
* The Network devtool shows the Bugzilla API returns 200/304, so the API seems ok
* The Console shows:

```
TypeError: this.bug.summary is undefined          combined.js:5520:8
TypeError: $tabpanel.querySelector(...) is null     combined.js:5815:4
```

**Comment by kyoshino** [comment]
Hmm, that's not good. Will test it tomorrow. Sorry I have been busy with other stuff :crying_cat_face:

**Comment by shinglyu** [comment]
No worries. I wish I can get familiar with the code and help you with these issues soon.
