### ISSUE TITLE
Comments are submitted twice

### ISSUE THREAD

**Issue by shinglyu** [bzdeck/bzdeck#303]
The comments are submitted twice on Bugzilla.

See bug 1200905 and bug 1165231.

I requested needinfo, not sure if its related.

**Comment by kyoshino** [comment]
Sorry @shinglyu, I have been busy. Will take a look.

**Comment by kyoshino** [comment]
I can't reproduce the issue so far. Will test again...

**Comment by kyoshino** [comment]
I can finally reproduce the issue today by moving back and forth between bugs then posting a comment. Will fix it soon. :weary:

**Comment by kyoshino** [comment]
Problem solved. Sorry for taking a long time to solve this.
