### ISSUE TITLE
Need a way to support formatting with fixed width font

### ISSUE THREAD

**Issue by shinglyu** [bzdeck/bzdeck#304]
See [bug 1165231 comment 2](https://bugzilla.mozilla.org/show_bug.cgi?id=1165231#c2)

The plain text table looks good on bugzilla, but scattered in BzDeck. Need some way to force it to format it.

Perhaps using a markdown syntax ? 
```
Like this
```

**Comment by kyoshino** [comment]
In the Settings, there is an option to use the Fira Mono font. Markdown syntax would be great, because we can use the fixed width font only for `<pre>` and `<code>`. But Markdown support has not enabled yet on bugzilla.mozilla.org. BzDeck's issue is #70.

**Comment by kyoshino** [comment]
#70 is unblocked now. This can be technically done.

**Comment by kyoshino** [comment]
Marking as a dup of #70. Will working on it shortly.
