### ISSUE TITLE
Unable to authenticate with bzdeck

### ISSUE THREAD

**Issue by riverspirit** [bzdeck/bzdeck#308]
Unable to authenticate with bzdeck. Showing error.
![alt text](https://cloud.githubusercontent.com/assets/712910/10380565/315cd0ce-6e32-11e5-846e-023fc18cbf15.png "Login error")

Browse usedr: Firefox Developer Edition 43.

**Comment by kyoshino** [comment]
I'm seeing the following error instead of the "invalid JSON" error:

> Auth delegation received an HTTP response other than 200 OK from auth consumer. Code: 301

I think [Bug 1175643](https://bugzilla.mozilla.org/show_bug.cgi?id=1175643) has not been deployed yet to BMO, and that's why #298 is open...

needinfo: @dylanwh

**Comment by kyoshino** [comment]
Gah, the patch already been [backported to BMO](https://github.com/mozilla/webtools-bmo-bugzilla/commit/589ec37a32d8687d612eedd107748b7afadd07fd) without any announcement. So it's broken for 2 months? WTF :confounded:

**Comment by kyoshino** [comment]
Fixed in #298.

**Comment by riverspirit** [comment]
Thank you!
