### ISSUE TITLE
Implement BzDeck Sidebar with Social API

### ISSUE THREAD

**Issue by kyoshino** [bzdeck/bzdeck#35]
It's a mini BzDeck... in your Firefox.

https://developer.mozilla.org/en-US/docs/Social_API
https://activations.cdn.mozilla.net/en-US/

**Comment by kyoshino** [comment]
The social API may work for basic features but the sidebar could be a Firefox extension like [JIRA Capture](https://www.atlassian.com/software/jira/capture) so the users can take screenshots to attach. Usually it is impossible to [capture Web page from other domains](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images#Using_images_from_other_domains) for security reasons. We could extend @shinglyu's extension developed in #250 in the future.

**Comment by shinglyu** [comment]
I saw someone demoed [this getUserMedia API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia), which can achieve something like a screensharing session. Not sure if we can use this to take screenshots.

**Comment by kyoshino** [comment]
Oh, I have heard that Firefox Hello will soon have [screen sharing](http://www.wired.co.uk/news/archive/2015-03/06/firefox-hello-video-call-upgrade). Not sure each Web site can utilize the functionality tho.

**Comment by kyoshino** [comment]
The [Social API has been removed](https://www.fxsitecompat.com/en-CA/docs/2016/social-api-has-been-removed-except-the-sharing-functionality/) with Firefox 51. This RFE is considered WONTFIX.
