### ISSUE TITLE
Use const in JS whenever possible

### ISSUE THREAD

**Issue by kyoshino** [bzdeck/bzdeck#380]
[`const`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const) is our friend.

Also, change assignment statements from

``` js
let a = 1,
    b,
    c;
```

to

``` js
const a = 1;
let b;
let c;
```

**Comment by kyoshino** [comment]
WONTFIXing this. I feel odd when using `const` for a couple of reasons.

**Comment by dylanwh** [comment]
Do you feel odd because const'd arrays/objects can still mutate? That's how I feel. We have the same issue in bugzilla.

**Comment by kyoshino** [comment]
Yes. It's just confusing.

**Comment by kyoshino** [comment]
Hmm, I want to try this again so that the code really looks like ES6. Theoretically `const` should be faster than `let` because the variable *type* won't change.
