### ISSUE TITLE
Bug comment textarea is not clickable

### ISSUE THREAD

**Issue by MikkCZ** [bzdeck/bzdeck#388]
Which blocks a e.g. possibility to right-click and change used spellchecker dictionary.

**Comment by kyoshino** [comment]
Thanks for your report! Personally I don't want to show any browser-native context menus on the app, but yes, spellchecking is essential on the comment box. I'll fix it.

**Comment by kyoshino** [comment]
Done. This will be live hopefully this weekend along with the Markdown support!

**Comment by kyoshino** [comment]
@MikkCZ See you soon in London!

**Comment by MikkCZ** [comment]
Great! :)
