### ISSUE TITLE
login with an email address including a + fails

### ISSUE THREAD

**Issue by Mozinet-fr** [bzdeck/bzdeck#390]
In the bzdeck error message the + is substitute with a space.

![auth_delegation_request-nightly](https://cloud.githubusercontent.com/assets/8845401/15908164/8c758c6e-2dc0-11e6-9ade-9a4669124621.png)
![bzdeck-nightly](https://cloud.githubusercontent.com/assets/8845401/15908165/8c981a90-2dc0-11e6-95e3-698b4552bc27.png)

**Comment by Mozinet-fr** [comment]
Bugzilla emails me: "A new Bugzilla API key, with the description 'BzDeck' has been created."

**Comment by kyoshino** [comment]
Thanks for your report! Will investigate the issue shortly.

**Comment by kyoshino** [comment]
Bad: https://bugzilla.mozilla.org/rest/user?names=mozinet+BMO@gmail.com
Good: https://bugzilla.mozilla.org/rest/user?names=mozinet%2BBMO@gmail.com

**Comment by kyoshino** [comment]
Okay, the fix will be pushed to production sometime soon. Thanks again for the report!
