### ISSUE TITLE
Wrong activity stream text for bug being added as blocked

### ISSUE THREAD

**Issue by MikkCZ** [bzdeck/bzdeck#391]
If someone adds a bug to the "blocked" list, between the comments appears a notice "#SOMEONE added Bug #NUMBER to blockers #TIME", which would indicate the added bug is blocking the current one, but it's the opposite way. The bug mentioned in the notice is being blocked by the current one being viewed.

**Comment by kyoshino** [comment]
Thanks for the report! Will check this out later.

**Comment by kyoshino** [comment]
Okay, I have changed the label from *blockers* to *blocked bugs*. Not perfect but better.
