### ISSUE TITLE
Submit button (for new bug comments) doesn't work on laptop with TouchScreen

### ISSUE THREAD

**Issue by jankeromnes** [bzdeck/bzdeck#394]
Thanks a lot for this amazing project! I look forward to using it more.

However, when I open a Bug from the Inbox, and I try to send a reply on my Windows 10 laptop (Dell XPS 13 with TouchScreen), the Submit button doesn't work.

When I inspect the page, I see that it only listens for "touchstart" events. The Attach button works however (it correctly listens for "click" instead).

Maybe on touch devices all buttons should listen for both "click" and "touchstart" events?

Thanks again!

**Comment by kyoshino** [comment]
@jankeromnes Thanks for your report! Will take a look.

**Comment by kyoshino** [comment]
References:

* [Touch/pointer events test results](https://patrickhlauke.github.io/touch/tests/results/)
* [Touch event support has been re-enabled on Windows desktop](https://www.fxsitecompat.com/en-CA/docs/2016/touch-event-support-has-been-re-enabled-on-windows-desktop/)

I think we should find a way to smartly handle both `touchstart` and `mousedown` with [FlareTail helpers.js](https://github.com/bzdeck/flaretail.js/blob/master/scripts/helpers.js), but I'll fix this specific bug first.

**Comment by kyoshino** [comment]
This is now fixed on production!
