### ISSUE TITLE
Text boxes and Search boxes shouldn't set `cursor: default` (they need `cursor: text` instead)

### ISSUE THREAD

**Issue by jankeromnes** [bzdeck/bzdeck#395]
In BzDeck, input fields force the `default` mouse pointer when you hover over them. This is confusing, because I expect the cursor to change to `text` on such input fields.

The offending line of CSS code is here: https://github.com/bzdeck/bzdeck/blob/d0d29bc0e209a25a33518caca36e0758b445131a/webroot/static/styles/base/widgets.css#L56

Please don't specify the `cursor` rule to let the browser choose the appropriate cursor, or at least please set `cursor: text` instead of `cursor: default` on `[role="textbox"]` and `[role="searchbox"]`. Thanks!

**Comment by kyoshino** [comment]
+1. Will fix it.

**Comment by kyoshino** [comment]
This is now fixed on production!
